### ISSUE TITLE
Retrieve Timesheet Endpoint (50 Response Limit)

### ISSUE THREAD

**Issue by kaburkett** [TSheetsTeam/api_docs#75]
Documentation mentions a response limit of 50 timesheets for create, update, and delete endpoints. On the receive timesheet endpoint, no limitation is mentioned. 

When I make requests to the retrieve endpoint, I only receive 50 timesheets as a response, no matter what timeframe I pass as parameters.

This might be a bug with the API and not the documentation. How is this supposed to be handled? My use case is to get all timesheets within one week, how do I do that?

**Comment by kaburkett** [comment]
I've also tried setting `&per_page=99999` as a parameter and I only receive 50 timesheets in a response.

**Comment by elloboblanco** [comment]
@kaburkett can you post a cURL example with all the parameters you are sending?

**Comment by kaburkett** [comment]
```
curl "https://rest.tsheets.com/api/v1/timesheets?start_date=2020-09-14&end_date=2020-10-13&on_the_clock=both"
  -H "Authorization: Bearer <TOKEN>" 
```

or

```
curl "https://rest.tsheets.com/api/v1/timesheets?start_date=2019-09-14&end_date=2020-10-13&on_the_clock=both"
  -H "Authorization: Bearer <TOKEN>" 
```

or

```
curl "https://rest.tsheets.com/api/v1/timesheets?start_date=2019-09-14&end_date=2020-10-13&on_the_clock=both&per_page=999"
  -H "Authorization: Bearer <TOKEN>" 
```

All return 50 timesheets in the response.

**Comment by kaburkett** [comment]
What's also interesting I've just noticed is the response has an additional object at the end: `more: true`.

```

        "results": {
            "timesheets": {
                "TIMESHEETID": {object} (50x)
                }
            }
        },
        "more": true,

```

**Comment by scottjeide** [comment]
Hi @kaburkett. The get calls are also limited to a maximum of 50 per page. If you want to retrieve more than timesheets than will fit in a single page, you will need to add the page=N argument to retrieve the additional pages. Start with page=1, and if you see  "more": true in the response, then there are additional pages available. In that case increment your page= argument and download the additional pages until more=false.

**Comment by kaburkett** [comment]
Ok, in this case the `per_page` parameter only works to return less than 50 results, I assume.

I can make these adjustments to our integration and see if this works for us.

**Comment by kaburkett** [comment]
This is working for us.

I am now noticing your notes on the retrieve endpoint under the per_page parameter:
```
per_page optional | Int | Represents how many results you'd like to retrieve per request (page). Default is 50. Max is 50.
```

I think what confused me was that the other endpoints for timesheets had disclaimers like:
`The maximum batch size is 50 timesheets. If exceeded, a 413: Request entity too large HTTP response will be returned.` but the receive endpoint did not.

A general note at the top of the documentation would also be kind. Maybe under the 'request throttling' section at the very top.

Thanks for your help.

**Comment by pgoswami3** [comment]
Hi @kaburkett - thanks for the notes _"To receive the full result, increment the page parameter and iterate through the requests until you receive "more":false as part of the response"_

I'm trying to wrap my head around on how to implement (multiple batch request/pagination) using the sample code from the [documentation](https://tsheetsteam.github.io/api_docs/#retrieve-jobcodes). I'm getting `"more" : true` in my initial call but how do you make the next call without getting the same data? Any ideas? :)

**Comment by kaburkett** [comment]
@pgoswami3 Hi Pratik, if I remember correctly, and based on @scottjeide comment above, you are required to add the page parameter onto the URL so an example would be:

`
curl "https://rest.tsheets.com/api/v1/timesheets?start_date=2020-09-14&end_date=2020-10-13&on_the_clock=both"
  -H "Authorization: Bearer <TOKEN>" 
  `
  
  Would need to have page=N appended like so for page one:
  
  `
  curl "https://rest.tsheets.com/api/v1/timesheets?start_date=2020-09-14&end_date=2020-10-13&on_the_clock=both&page=1"
  -H "Authorization: Bearer <TOKEN>" 
  `
  
  Then for page two increment it again:
  
  `
  curl "https://rest.tsheets.com/api/v1/timesheets?start_date=2020-09-14&end_date=2020-10-13&on_the_clock=both&page=2"
  -H "Authorization: Bearer <TOKEN>" 
  `
  
  Repeat the process of incrementing the page # making new requests and compiling responses until the response has more: false. Not extremely easy to use, but, it works.

**Comment by pgoswami3** [comment]
Thank you so much, Kyle @kaburkett

**Comment by kaburkett** [comment]
Very cool, thanks. It will help future Dev when reading docs
